global:
  smtp_from: 'alertmanager@qq.com'
  smtp_smarthost: 'smtp.qq.com:25'
  smtp_auth_username: 'USER'
  smtp_auth_password: 'PASSWD'
  smtp_require_tls: false

templates:
  - '/etc/altermanager/template/*.tmpl'

route:
  group_by: ['instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: email
  routes:
  - match:
      severity: critical
    receiver: pager
  - match_re:
      severity: ^(warning|critical)$
    receiver: support_team
receivers:
  - name: 'email'
    email_configs:
      - to: 'user1@email'
  - name: 'support_team'
    email_configs:
      - to: 'user2@126.com'
  - name: 'pager'
    email_configs:
      - to: 'user3@qq.com'
